# platform :ios, '8.0'

target 'PLLock' do

pod 'LGSideMenuController', '2.1.1'
pod 'AFNetworking', '3.1.0'
pod 'MBProgressHUD', '1.0.0'
pod 'iConsole', '1.5.3'
pod 'TZImagePickerController', '1.7.9'
pod 'SVProgressHUD', '2.1.2'
pod 'LGPlusButtonsView', '1.1.1'
pod 'GCDWebServer/WebUploader'


pod 'FBAudienceNetwork'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/AdMob'

end
