# platform :ios, '8.0'

target 'PLLock' do

pod 'LGSideMenuController', '2.1.1'
pod 'AFNetworking', '3.1.0'
pod 'iConsole', '1.5.3'
pod 'TZImagePickerController', '1.7.9'
pod 'MBProgressHUD', '~> 0.9'
pod 'LGPlusButtonsView', '1.1.1'
pod 'GCDWebServer/WebUploader'
pod 'DACircularProgress', '2.3.1'
pod 'SDWebImage', '3.8.2'

pod 'FBAudienceNetwork'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/AdMob'

end
